### ISSUE TITLE
Admin Dashboard Layout

### ISSUE THREAD

**Issue by ulrokx** [stevensblueprint/aad-admin#119]
For the admin dashboard, we will use pages wrapped with a layout component.

Since the app will have multiple layouts, the following link will help work with Nextjs

https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#per-page-layouts

This layout component should have a menu with options that redirect to different admin pages (/collections, /forms)

**Comment by miguel-merlin** [comment]
Closed by #137
