### ISSUE TITLE
Profile editing screen

### ISSUE THREAD

**Issue by ulrokx** [stevensblueprint/aad-admin#126]
As a user(mentee and mentor), I should be able to edit my profile

I can edit my name, school, industries of interest, and blurb.

Some reasonable constraints should be placed on the types for validation, use zod schema for this.

School should be a dropdown of schools, maybe find list or api?
Industries should be limited to a list somewhere, can be incomplete for now. Will make another issue to find the wanted list of industries. This should be a multiselect component, perhaps this https://mui.com/material-ui/react-select/#system-MultipleSelectChip.tsx

Blurb is a mui textarea

This page should be accessible from the profile page.

**Comment by ShawnAviles** [comment]
Links to datasets with colleges/universities:
- https://nces.ed.gov/ipeds/use-the-data
- https://github.com/endSly/world-universities-csv/blob/master/world-universities.csv

**Comment by ShawnAviles** [comment]
What is this in relation to the profile page? Is their a user flow I could follow. Is this not the profile page itself as well? I have been trying to follow something along the lines of [this from the Figma](https://www.figma.com/file/AzMhLprCGJu2ED77fb0VDn/Asian-American-Dream-Pages?type=design&node-id=0-1&mode=design&t=sCguLHXxkVzdWKK3-0)

![Screenshot 2024-03-04 at 11 43 27 PM](https://github.com/stevensblueprint/aad-admin/assets/43704084/c43880d5-0a4e-40ea-ae1f-f088c0d55cb7)

How is this different from the "Profile Page"? @ulrokx

**Comment by ulrokx** [comment]
This looks like an edit profile screen; those look like text inputs. The profile page won't have text inputs.
