### ISSUE TITLE
Add pre-commit hooks for linting/formatting

### ISSUE THREAD

**Issue by ulrokx** [stevensblueprint/aad-admin#9]
To avoid merge conflicts and badly formatted/unlinted code, we should have a [GitHub status check](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks) for each commit to ensure it is linted and formatted. 

This also required the repository having a formatter and linter configured. I believe Nextjs comes with an eslint config, and the starter template we used has one as well, so verify these work and use them for the GitHub status check.

**Comment by ulrokx** [comment]
@ericzty can you work with Harris on this and you two figure out best way of doing this?

**Comment by ericzty** [comment]
@ulrokx sounds good, I just had my first meeting with Harris and discussed the first steps on getting this rolling.

First we will figure out how to configure github actions with eslint w/ nextjs / t3. Then github actions should be able to interpret the linter's exit code and notify us if it fails.

We also discussed some future plans for the devops pipeline, like  unit/integration tests, releases, and also building into containers.
