### ISSUE TITLE
Mentor Selection Page

### ISSUE THREAD

**Issue by ulrokx** [stevensblueprint/aad-admin#90]
# User Matching Page

### Description
Page exists at `/matching` path and requires user to log in before filling it out. Based on the users role:
- Mentees have event (triggered by Admin) to choose mentors. Page where they can choose and rank mentors 1-5.
- Mentors have event (triggered by Admin) to choose mentees. Page where they can choose and rank mentees 1-5.

### DOD
- Auto complete search box for selecting 5 mentees/mentors
- Drag and drop for selecting top 5 from those that were selected. [[react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)]
- Submit button that submits 5 mentee/mentor ids in order.

Not using this anymore: https://www.figma.com/file/AzMhLprCGJu2ED77fb0VDn/Asian-American-Dream-Pages?type=design&node-id=0-1&mode=design

**Comment by ShawnAviles** [comment]
# Goal 

Easily be able to see it on phone or computer, be able to view all Users (mentees or mentors) and select your top 5.

## Options:

### ❌ Using New Collection (JSON Forms): 
- no go, trying to make it do something it is not meant for 
- over complicated

### ✅ Custom Feature
- Need to able to select 5 users

**Admin**
- be able to open, close, clear
- page in Admin Dashboard 

**Mentee / Mentor**
- Able to fill it out top 5 five
- Page that is linkable
- Submit button which submits list of 5 mentee IDs

some more issues will be created to elaborate on this...
